"""
ClipForge AI — Pipeline Orchestrator (v2)

Chains the v2 pipeline stages with granular status tracking:
  1. Ingest / Download (`download_source`)
  2. Unified Analysis (`run_analysis`: Whisper + SceneDetect + MediaPipe)
  3. LLM Candidate Selection (`select_clips`: brief-aware + transformation scoring + scene snapping)
  4. Professional Rendering (`render_project_clips`: 9:16 reframe, ASS captions, loudnorm, manifests)
"""
import logging
import uuid
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy.orm import Session

from clipforge_core.celery_app import celery_app
from clipforge_core.config import settings
from clipforge_core.database import get_sync_session
from clipforge_core.models import Job, Project
from clipforge_core.workers.analysis import run_analysis
from clipforge_core.workers.download import download_source
from clipforge_core.workers.render import render_project_clips
from clipforge_core.workers.select import select_clips

logger = logging.getLogger(__name__)

PIPELINE_STAGES = ["download", "transcribe", "select", "crop", "caption"]


def create_pipeline_jobs(project_id: str, session: Session | None = None) -> list[dict]:
    """Create job records for all pipeline stages."""
    close_session = False
    if session is None:
        session = get_sync_session()
        close_session = True

    try:
        jobs = []
        for stage in PIPELINE_STAGES:
            job = Job(
                id=uuid.uuid4(),
                project_id=uuid.UUID(project_id),
                stage=stage,
                status="pending",
                updated_at=datetime.now(timezone.utc),
            )
            session.add(job)
            jobs.append({"id": str(job.id), "stage": stage, "status": "pending"})

        session.commit()
        logger.info(f"Created {len(jobs)} pipeline jobs for project {project_id}")
        return jobs
    except Exception as e:
        session.rollback()
        logger.error(f"Failed to create pipeline jobs: {e}")
        raise
    finally:
        if close_session:
            session.close()


def _update_job(project_id: str, stage: str, status: str, error_message: str | None = None) -> None:
    """Update a specific job stage status."""
    session = get_sync_session()
    try:
        job = (
            session.query(Job)
            .filter(
                Job.project_id == uuid.UUID(project_id),
                Job.stage == stage,
            )
            .first()
        )
        if job:
            job.status = status
            job.error_message = error_message
            if status == "running":
                job.started_at = datetime.now(timezone.utc)
            if status in ("success", "failed"):
                job.completed_at = datetime.now(timezone.utc)
            session.commit()
    except Exception as e:
        logger.error(f"Failed to update job {stage}: {e}")
        session.rollback()
    finally:
        session.close()


def _update_project(project_id: str, status: str) -> None:
    """Update project-level status."""
    session = get_sync_session()
    try:
        project = session.query(Project).filter(Project.id == uuid.UUID(project_id)).first()
        if project:
            project.status = status
            session.commit()
    except Exception as e:
        logger.error(f"Failed to update project status: {e}")
        session.rollback()
    finally:
        session.close()


def dispatch_pipeline(project_id: str, project: Project) -> str:
    """
    Dispatch the full v2 pipeline as a distributed Celery chain across dedicated queues.
    """
    from celery import chain as celery_chain

    # source_path is predictably generated by download_source
    source_path = str(Path(settings.MEDIA_DIR) / project_id / "source.mp4")
    
    # We use .si() (immutable signatures) because each task fetches the state it needs
    # rather than passing large dicts between celery workers.
    pipeline = celery_chain(
        download_source.si(
            project_id=project_id,
            source_type=project.source_type,
            source_value=project.source_value,
        ),
        run_analysis.si(
            project_id=project_id,
            source_path=source_path,
        ),
        select_clips.si(
            project_id=project_id,
            clip_count=project.clip_count,
            min_length_sec=project.min_length_sec,
            max_length_sec=project.max_length_sec,
            custom_prompt=None,
            time_range_start=project.time_range_start,
            time_range_end=project.time_range_end,
            temporal_distribution=project.temporal_distribution,
            content_focus=project.content_focus,
        ),
        render_project_clips.si(
            project_id=project_id,
        )
    )

    result = pipeline.apply_async()
    logger.info(f"[Pipeline] Dispatched distributed v2 chain for project {project_id} (task_id={result.id})")
    return str(result.id)


def dispatch_reclip(
    project_id: str,
    clip_count: int = 5,
    min_length_sec: int = 20,
    max_length_sec: int = 60,
    aspect_ratio: str = "9:16",
    caption_style: str = "bold_karaoke",
    custom_prompt: str | None = None,
    time_range_start: float | None = None,
    time_range_end: float | None = None,
    temporal_distribution: str = "even_spread",
    content_focus: str = "balanced",
) -> str:
    """
    Re-run select -> render pipeline.
    """
    # Reset downstream jobs to pending
    session = get_sync_session()
    try:
        jobs = session.query(Job).filter(
            Job.project_id == uuid.UUID(project_id),
            Job.stage.in_(["select", "crop", "caption", "render"])
        ).all()
        for j in jobs:
            j.status = "pending"
            j.progress_percent = None
            j.progress_detail = None
        session.commit()
    except Exception as e:
        logger.error(f"Failed to reset jobs for reclip: {e}")
        session.rollback()
    finally:
        session.close()

    from celery import chain as celery_chain

    reclip_chain = celery_chain(
        select_clips.si(
            project_id=project_id,
            clip_count=clip_count,
            min_length_sec=min_length_sec,
            max_length_sec=max_length_sec,
            custom_prompt=custom_prompt,
            time_range_start=time_range_start,
            time_range_end=time_range_end,
            temporal_distribution=temporal_distribution,
            content_focus=content_focus,
        ),
        render_project_clips.si(project_id=project_id),
    )

    result = reclip_chain.apply_async()
    logger.info(f"[Pipeline] Dispatched reclip chain for project {project_id} (task_id={result.id})")
    return str(result.id)
