"""create_v2_tables

Revision ID: 4c21671da280
Revises: 001_initial
Create Date: 2026-09-01 19:05:08.985053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c21671da280'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_kits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('primary_color', sa.Text(), server_default=sa.text("'#6366F1'"), nullable=False),
    sa.Column('secondary_color', sa.Text(), server_default=sa.text("'#10B981'"), nullable=False),
    sa.Column('font_family', sa.Text(), server_default=sa.text("'Montserrat'"), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('watermark_position', sa.Text(), server_default=sa.text("'top_right'"), nullable=False),
    sa.Column('default_cta_text', sa.Text(), server_default=sa.text("'Subscribe for more'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), server_default=sa.text("'Local Workspace (Solo Creator)'"), nullable=False),
    sa.Column('mode', sa.Text(), server_default=sa.text("'local_first'"), nullable=False),
    sa.Column('tier', sa.Text(), server_default=sa.text("'free_studio'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brief_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_briefs_owner', 'campaign_briefs', ['owner_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_value', sa.Text(), nullable=False),
    sa.Column('campaign_brief_id', sa.UUID(), nullable=True),
    sa.Column('clip_count', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('min_length_sec', sa.Integer(), server_default=sa.text('20'), nullable=False),
    sa.Column('max_length_sec', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('aspect_ratio', sa.Text(), server_default=sa.text("'9:16'"), nullable=False),
    sa.Column('caption_style', sa.Text(), server_default=sa.text("'bold_karaoke'"), nullable=False),
    sa.Column('editorial_template', sa.Text(), server_default=sa.text("'explainer'"), nullable=False),
    sa.Column('rights_basis', sa.Text(), server_default=sa.text("'owned'"), nullable=False),
    sa.Column('rights_proof_url', sa.Text(), nullable=True),
    sa.Column('rights_notes', sa.Text(), nullable=True),
    sa.Column('source_risk_label', sa.Text(), server_default=sa.text("'lower_workflow_risk'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("aspect_ratio IN ('9:16', '1:1', '16:9')", name='ck_projects_aspect_ratio'),
    sa.CheckConstraint("rights_basis IN ('owned', 'written_permission', 'authorized_campaign', 'commentary_review', 'other_unconfirmed')", name='ck_projects_rights_basis'),
    sa.CheckConstraint("source_type IN ('youtube_url', 'local_folder', 'upload')", name='ck_projects_source_type'),
    sa.ForeignKeyConstraint(['campaign_brief_id'], ['campaign_briefs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_owner_created', 'projects', ['owner_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('transformation_score', sa.Integer(), nullable=True),
    sa.Column('transformation_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('render_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_status IN ('pending', 'approved', 'rejected')", name='ck_clips_review_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clips_project_review', 'clips', ['project_id', 'review_status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'success', 'failed', 'retrying')", name='ck_jobs_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_project_stage', 'jobs', ['project_id', 'stage'], unique=False)
    op.create_table('project_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_events_project_time', 'project_audit_events', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('source_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('video_codec', sa.Text(), nullable=True),
    sa.Column('audio_codec', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_assets_project', 'source_assets', ['project_id'], unique=False)
    # ### end Alembic commands ###
    
    # Add updated_at trigger for jobs table
    op.execute("""
    CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
    BEGIN
        NEW.updated_at = now();
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    
    op.execute("""
    CREATE TRIGGER jobs_updated_at
        BEFORE UPDATE ON jobs
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS jobs_updated_at ON jobs;")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")
    op.drop_index('idx_source_assets_project', table_name='source_assets')
    op.drop_table('source_assets')
    op.drop_index('idx_audit_events_project_time', table_name='project_audit_events')
    op.drop_table('project_audit_events')
    op.drop_index('idx_jobs_project_stage', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_clips_project_review', table_name='clips')
    op.drop_table('clips')
    op.drop_index('idx_projects_owner_created', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_campaign_briefs_owner', table_name='campaign_briefs')
    op.drop_table('campaign_briefs')
    op.drop_table('workspaces')
    op.drop_table('users')
    op.drop_table('brand_kits')
    # ### end Alembic commands ###

