"""add_job_progress_columns

Revision ID: 70e87509f319
Revises: 7a1b2c3d4e5f
Create Date: 2026-09-04 15:11:30.483777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70e87509f319'
down_revision: Union[str, None] = '7a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('progress_percent', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('progress_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'progress_detail')
    op.drop_column('jobs', 'progress_percent')
    # ### end Alembic commands ###
